### PR TITLE
Let's Encrypt integration

### PR DESCRIPTION
**Pull request by lipis**
From: http://blog.seafuj.com/lets-encrypt-on-google-app-engine

### CODE REVIEW

**Comment by lipis** [comment]
When I'm trying to:

```bash
sudo openssl rsa -inform pem -in /etc/letsencrypt/live/www.example.com/privkey.pem -outform pem | less
```
I'm getting the following error:

```bash
unable to load Private Key
139684947035792:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY
```

**Comment by lipis** [comment]
From the Cloud Console
screen shot 2015-12-07 at 10 44 09

**Comment by gmist** [comment]
I have not tried it, but here [1](http://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6), [2](http://blog.assarbad.net/20120920/ssl-error-with-a-newly-signed-cert/) a similar problem is solved.

**Comment by lipis** [comment]
the file is being generated.. but the folder has some really strange file rights.. :/

**Comment by lipis** [comment]
http://igorartamonov.com/2015/12/lets-encrypt-ssl-google-appengine/

**Comment by lipis** [comment]
So it worked quite nicely and I collected the actual steps that needed with the help of this branch in the how to section.. http://docs.gae-init.appspot.com/howto/#letsencrypt

https://lip.is :)

**Comment by lipis** [comment]
screen shot 2015-12-13 at 22 30 00

**Comment by lipis** [comment]
It works :)

**Pull request merged**
