### PR TITLE
Explicitly check for method.

### PR DESCRIPTION
**Pull request by topless**
When I am trying to post a json array in the api, I get `AttributeError: 'list' object has no attribute 'get'`. Can someone enlighten me about the usage of lines, 21, 22? When I work, with json requests I use the `flask.request.get_json()` as suggested from flask 0.10.

### CODE REVIEW

**Comment by gmist** [comment]
Hmm... for POST requests you need to set the request content_type to ```application/json```

**Comment by lipis** [comment]
Is that still valid..? I'm thinking of merging the #454..

**Comment by topless** [comment]
I forgot to reply on this one, the `application/json` headers are there as they are supposed to. The problem occurs when I am posting a json array object like `[1, 2, 3]` and try to store it as json property.
If I do like {data: [1, 2, 3]} in can properly iterates on the params. Do I make any sense? or I should try to write it in English. This commit is just skipping the util param when its a POST, its not fixing anything.

**Comment by topless** [comment]
Go ahead and merge 454, much cleaner approach.

**Pull request closed without merging**
