### PR TITLE
Remove confusing main/__init__.py

### PR DESCRIPTION
**Pull request by rbubley**
Related to Issue #420, and some conversations on slack, this PR removes `main/__init__.py`, and instead allows `run.py` to more explictly load only what's needed.

Positive side effects:
* it makes it clearer to see configuration variables shared between `run.py` and the main code
* it will enable a future tidy-up of `main/config.py`
* it will make mean there is no longer an ability for PyCharm CE or developers to be confused between `main` (the module) and `main.py`

### CODE REVIEW

**Comment by mdxs** [comment]
Shouldn't the new `main/run_helper.py` at least have some `# coding: utf-8` on the top?
And perhaps add a doc string on what the possible purpose of it is.

**Comment by mdxs** [comment]
Sorry, I only now realise that it was a move... I thought the file was empty, but instead the new `main/run_helper.py` is the old `main/__init__.py`; so please ignore my comment.

**Comment by lipis** [comment]
Actually just delete it and add the `__version__ = '5.8.0'` inside the `run.py` and all the problems are solved. As for the description.. we'll think something else :)

**Comment by rbubley** [comment]
I can do -- but the approach I proposed is:

1.  trivially compatible with gae-init-babel, which needs to import other configuration information
2. means that the main code could have access to the version number. Not sure if this is actually useful or not, but it feels like it might be.

**Comment by lipis** [comment]
I will use that there instead..

```
config = imp.load_source('config', 'main/config.py')
```

**Comment by lipis** [comment]
Re. 2. Not really.. as this version has to do with gae-init it self and I believe it's irrelevant with the actual app. User's might want to keep their own versions elsewhere..

**Comment by lipis** [comment]
Awesome! Thanks..

**Pull request merged**
