### PR TITLE
Travis test

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by rbubley** [comment]
Looks like 2.7.16 is not available on Travis

**Comment by lipis** [comment]
Very strange

**Comment by rbubley** [comment]
Merge in #1204 — and it works.

**Comment by rbubley** [comment]
Looks like there was a merge issue -- the fixes from #1204 aren't in master, so the builds are still failing.

**Comment by lipis** [comment]
hmm.. can you create a new PR?

**Pull request closed without merging**
