### PR TITLE
Gulp 4

### PR DESCRIPTION
**Pull request by rbubley**
Migrate to Gulp 4.

### CODE REVIEW

**Comment by lipis** [comment]
Travis is complaining..

**Comment by lipis** [comment]
Great stuff by the way!!! ❤️

**Comment by rbubley** [comment]
Getting closer, Travis still complaining though...

**Comment by lipis** [comment]
🍻🍺🍻🍺

**Comment by lipis** [comment]
Travis is green!! I'll play with it over the weekend to test it in some of my older projects..! Thanks a bunch for this..

**Comment by lipis** [comment]
Works nicely with Node 12 :)

Great job @rbubley! Thanks a lot for this..

**Comment by lipis** [comment]
I'm merging this one.. looks great! Thanks again..

**Pull request merged**
