### PR TITLE
Remove GAE_PYTHONPATH, and check correct SDK path instead

### PR DESCRIPTION
**Pull request by rbubley**
…which hopefully fixes the lack of cacheing.

### CODE REVIEW

**Comment by lipis** [comment]
not green :)

**Comment by rbubley** [comment]
If only I knew how to test changes to travis.yml, locally! Will figure it out and fix it up.

**Comment by lipis** [comment]
Let me know when it's ready and I'll merge it..

**Comment by rbubley** [comment]
OK - I think it's ready!

**Pull request merged**
