### PR TITLE
Allow to get maximum results from query

### PR DESCRIPTION
**Pull request by gmist**
```
limit
Maximum number of results to return. If set to None, all available results will be retrieved.
```
[from here](https://cloud.google.com/appengine/docs/python/ndb/queryclass#kwdargs_options)

Example:
``` python
  user_dbs, _ = model.User.get_dbs(email=util.param('email'), limit=None)
```
It returns all available users from the DB.

### CODE REVIEW

**Comment by gmist** [comment]
I'm sorry, but it breaks the logic of the function util.param()... Is better to roll back to version 3a677f038e432737e7a59c3896c55af1d3b3da95

**Comment by gmist** [comment]
Maybe something like [that](https://github.com/gmist/five-studio2/commit/09b9b8986e7f2e002aaea97c6520bf34a2fcbb55#diff-873b25319843fdb5d75c9fad811dcbeeR77)

and somewhere in a template
``` html
        <button type="button" class="btn btn-primary" disabled>Limit</button>
        {{utils.filter_by_link('limit', 16)}}
        {{utils.filter_by_link('limit', 64)}}
        {{utils.filter_by_link('limit', -1, label='All')}}
```

**Comment by lipis** [comment]
No problem.. rolled it back for now.. will check tomorrow for the alternatives :) cheers..

**Comment by lipis** [comment]
@gmist yes something like that should be good to go.. Like a little easter egg with the `-1`

**Comment by lipis** [comment]
@gmist Create a new PR if you like.. :)

**Pull request merged**
