### PR TITLE
Updated momentjs

### PR DESCRIPTION
**Pull request by mdxs**

### CODE REVIEW

**Comment by lipis** [comment]
I wonder why the dependabot didn't catch that one... you should update the package-lock too

**Comment by mdxs** [comment]
Okay, will need to look into that...

**Comment by mdxs** [comment]
Is it perhaps because "momentjs" is in the ``bower.json`` and not in ``package.json`` (and also not in ``package-lock.json``?

**Comment by lipis** [comment]
dah!! :) I was so used to that.. :)

**Pull request merged**
