### PR TITLE
added comment for lib.zip

### PR DESCRIPTION
**Pull request by brubakerjeff**
Based upon our conversation please let me know if this comment is acceptable.

### CODE REVIEW

**Comment by lipis** [comment]
I'm just not sure if we really need a comment here..

**Comment by brubakerjeff** [comment]
Coming from a non author working on derived work I can stare I have spent over two years not knowing how this worked. Wether or not a comment here is appropriate is debatable but I recommend a documentation update somewhere for the next person.

**Comment by mdxs** [comment]
Rather than a PR to add this as a inline comment, perhaps PRs to improve the surrounding documentation?

As it is, the comment on the else is actually incorrect.

**Comment by brubakerjeff** [comment]
agreed for updating documentation and I see where it is maintained now. https://github.com/gae-init/gae-init-docs

**Pull request closed without merging**
