### PR TITLE
Make historical starting date inclusive

### PR DESCRIPTION
**Pull request by mdxs**
The historical starting date of 2012-01-01 should be included to avoid not having statistics for that date... Proposing to change (even if you did only party that day, or sleeping; or whatever) as others implementing stats should by default include such a historical/theoretical starting date; which they should probably set (close) to their launch date.

### CODE REVIEW

**Comment by mdxs** [comment]
Note that this belongs in the #473 Stats example.

**Comment by lipis** [comment]
I would prefer that to be a comment instead of PR.. as it's very very small change and usually the whole `example` is squashed :D changed it there..

**Comment by mdxs** [comment]
Okay, will try to remember next time ;-)

**Comment by lipis** [comment]
💃 🍻 📈 📊

**Pull request closed without merging**
