### PR TITLE
Fix stubs import error

### LINKED ISSUE #797: Stubs again
I've recently started seeing:
```
Traceback (most recent call last):
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/<redacted>/main/appengine_config.py", line 19, in <module>
    from google.appengine.tools.devappserver2.python.runtime import stubs
ImportError: cannot import name stubs
```

This is with gae-init 5.10.0, so includes the changes from  #719.

Anyone else seeing this, or is it something up with my environment?

### PR DESCRIPTION
**Pull request by lipis**
Should fix #797 #713 

If anyone has any better.. let me know :)

### CODE REVIEW

**Comment by daspots** [comment]
I implemented your fix but now my css doesn't link anymore...have you seen this problem before? 
Thanks!

**Comment by lipis** [comment]
If you can post the exact error.. would be helpful :)

**Comment by daspots** [comment]
Thanks for your fast response. I checked my Stylesheet, typos inside my HTML and CSS, and fatal errors but didn't see anything unusual. A screenshot below:
printscreen

**Comment by lipis** [comment]
`database is locked`

Try running `gulp flush` and `gulp clean` and then start the whole thing again.

**Comment by daspots** [comment]
Thanks, will try

**Comment by daspots** [comment]
unfortunatly didn't work, now I get a warmup request error...do you know what this means (i'm new to this so really appreciate you helping me)
printscreen

**Pull request merged**
