### PR TITLE
Fix sign in refresh issues

### LINKED ISSUE #414: Sign-in not working properly on Chrome
I encounter this reproducible problem on Chrome, but not Firefox or Safari.
1. Go to https://gae-init.appspot.com/
2. Log out (if logged in), and click on "gae-init" in the nav bar.
3. Click on Log in.
4. Select Facebook, authenticate with facebook if necessary

Result: Page still says Sign In. But if you refresh, you can then see that you are logged in.

### PR DESCRIPTION
**Pull request by lipis**
Not the prettiest, but it does the trick.

Fixes #414

### CODE REVIEW

**Comment by gmist** [comment]
It's dirty, but I see no other solution :(

``` python
next_url = util.get_next_url(auth_params['next'])
next_url = '%s%s%s' % (next_url, '&' if '?' in next_url else '?', time.time())
```

``` python
from uuid import uuid4 as uuid
import time
import timeit

def a():
    '%s' % uuid().hex[:4]

def b():
    '%s' % time.time()

print timeit.timeit('a()', 'from __main__ import a', number=10000)
print timeit.timeit('b()', 'from __main__ import b', number=10000)
```
results:
```
0.147270917892
0.00507283210754
```

**Comment by rbubley** [comment]
There are trade-offs to be made here. If there was the simpler:
`next_url = '%s%s' % (next_url, '&loggedin' if '?' in next_url else '?loggedin)`

It would be faster, but would bump into this bug only if a user logged in and out with multiple userids. I suspect this multiple userid issue is an issue only for testers not real users.

**Comment by gmist** [comment]
``` python
next_url = '%s%sloggedin=%s' % (next_url, '&' if '?' in next_url else '?', user_db.id)
```

**Comment by lipis** [comment]
I wanted to keep it as short as possible and exposing the ID into the browser history.. might not be OK in some cases :) But based on that.. what about something like that:

```python
    next_url = '%s%s%s' % (next_url, '&' if '?' in next_url else '?', user_db.key.urlsafe()[-4:])
```

**Comment by NoahWilcox** [comment]
It works perfectly for me now. Thank you!

**Comment by lipis** [comment]
I'm going with this! :)

**Pull request merged**
