### PR TITLE
Now after npm install and gulp init the gulp command will execute aut…

### PR DESCRIPTION
**Pull request by topless**
…omatically.

### CODE REVIEW

**Comment by topless** [comment]
As lazy as it gets as you can see..

**Comment by lipis** [comment]
Maybe we could print on how to start there but with the `npm install` I don't want anything to start that doesn't end..

Something like that? WDYT?

```json

"postinstall": "echo 'Run `gulp` to start or `gulp help` for more.'"
```

**Comment by topless** [comment]
That could work too, to display the next step you have to take. I was just showing off about `postinstall`

**Comment by topless** [comment]
It prints the command twice, once as a postinstall command and once the echo of the postinstall command. If you like it we keep it.

screen shot 2016-10-24 at 15 46 09

**Pull request merged**
