### PR TITLE
Remove coffeescript and gulp-help; add gulp-help-doc

### LINKED ISSUE #1214: Translate gulp tasks from CoffeeScript to JS

### LINKED ISSUE #1331: gulp-help is a blocker to upgrading to gulp4
Suggest replacing with gulp-help-doc.

### PR DESCRIPTION
**Pull request by rbubley**
Should resolve #1331  (gulp-help is a blocker to gulp4)
To get it to work, I had to move away from coffeescript, which inter alia resolves #1214

### CODE REVIEW

**Comment by lipis** [comment]
It would be nice to keep CoffeeScript for backwards compatibility if some old projects still using CoffeeScript.. but I don't mind having it converted to JS the gulp scripts. Can we keep CoffeeScript for that?

**Comment by rbubley** [comment]
> It would be nice to keep CoffeeScript for backwards compatibility if some old projects still using CoffeeScript.. but I don't mind having it converted to JS the gulp scripts. Can we keep CoffeeScript for that?

Do you mean coffeescript compatibility for custom gulp tasks, or for for things in {paths.src.script}/**/*.coffee (or both)?

**Comment by lipis** [comment]
no no.. not for custom gulp tasks.. only for things in `src/script`

**Comment by rbubley** [comment]
OK, I’ll put that back in.

**Comment by lipis** [comment]
Is this ready?

**Comment by rbubley** [comment]
Yes.

**Comment by lipis** [comment]
Then can you fix the conflicts so we can merge this?

**Comment by rbubley** [comment]
I'm sure it didn't have conflicts when I submitted it! I'll fix...

**Comment by lipis** [comment]
To the next one :)

**Pull request merged**
