### PR TITLE
Remove prefetch link on auth

### PR DESCRIPTION
**Pull request by lipis**
Related to #608

### CODE REVIEW

**Comment by lipis** [comment]
Can anyone verify this?! Explains quite a few things.. why chrome was behaving like that :)

**Comment by gmist** [comment]
it seems to solve the problem

**Comment by lipis** [comment]
👍

**Comment by mdxs** [comment]
Seems to work for me, but I had issues to reproduce the error; so I might just be on the happy path ;-)

**Comment by lipis** [comment]
Thanks @mdxs :) If it works.. then we are good.. hehe

**Pull request merged**
