### PR TITLE
Check cache properly; delete all cached files on version update

### PR DESCRIPTION
**Pull request by rbubley**
Hopefully fixes travis issue @lipis raised in #952

### CODE REVIEW

**Comment by lipis** [comment]
nope :(

**Comment by lipis** [comment]
success

**Comment by lipis** [comment]
thanks

**Comment by rbubley** [comment]
I'm not totally convinced the Travis google cloud sdk cacheing is working properly yet, but that is an optimization only and shouldn't (!) stop it working.

**Comment by lipis** [comment]
we will see

**Pull request merged**
