### PR TITLE
Added Reddit OAuth

### PR DESCRIPTION
**Pull request by lipis**
So for some reason when I set the `redirect uri` to `httpS` on Reddit's side.. it doesn't work.. It tries to redirect to `http` and it fails..

screen shot 2015-05-05 at 23 20 58

Here is how the URL looks like even though in the settings I have it defined with HTTPS :/
```
https://ssl.reddit.com/api/v1/authorize?response_type=code&client_id=XXXXX&redirect_uri=http%3A%2F%2Fgae-init.appspot.com%2Fapi%2Fauth%2Fcallback%2Freddit%2F&scope=identity&state=0b2f9941a58c4eeb8e2c01e69e2c3f61
```

### CODE REVIEW

**Comment by lipis** [comment]
So for some reason when I set the URL to HTTPS on Reddit's side.. it doesn't work.. It tries to redirect to http and it fails..

screen shot 2015-05-05 at 23 20 58

Here is how the URL looks like even though in the settings I have it defined with HTTPS :/
```
https://ssl.reddit.com/api/v1/authorize?response_type=code&client_id=XXXXX&redirect_uri=http%3A%2F%2Fgae-init.appspot.com%2Fapi%2Fauth%2Fcallback%2Freddit%2F&scope=identity&state=0b2f9941a58c4eeb8e2c01e69e2c3f61
```

**Comment by lipis** [comment]
Is it the same on your side @gmist?

**Comment by gmist** [comment]
At first view I have the same problem, tomorrow I'll check it attentively.

**Comment by lipis** [comment]
Thanks, I filed a bug report anyway :) http://www.reddit.com/r/bugs/comments/34zlne/when_i_set_the_redirect_uri_to_https_in_my_reddit/

**Comment by lipis** [comment]
I _smells_ like it should be here: https://github.com/lipis/gae-init/blob/reddit-oauth/main/auth/reddit.py#L36

**Comment by gmist** [comment]
In ```flask_oauthlib/client.py``` line 518
``` python
def authorize(self, callback=None, state=None, **kwargs):
  ...
  session['%s_oauthredir' % self.name] = callback
  ...
```
so I think that the problem is not here

**Comment by lipis** [comment]
but on Reddit's side?

**Comment by gmist** [comment]
No, but I think I found the problem...

**Comment by lipis** [comment]
Messed it up with the squashes mashes lashes.. but I think now I know :)

p89inhk

**Comment by lipis** [comment]
Live: https://gae-init.appspot.com/signin/

**Pull request merged**
