### PR TITLE
use vendor.add to read venv directory instead of copying libs

### PR DESCRIPTION
**Pull request by jakedotio**
This is my attempt at a fix for https://github.com/gae-init/gae-init/issues/616

Feedback welcomed

### CODE REVIEW

**Comment by lipis** [comment]
@jakedotio Did you test it on production?! Another breaking change that will be hard to pass on.. :/

**Comment by jakedotio** [comment]
Yes, I did, but probably wasn't clear that I'm still working on this and it's a work in progress for now.

**Comment by lipis** [comment]
Potentially fixed in #685

**Comment by mdxs** [comment]
Can we conclude that #685 fixed the issue and that this PR #619 can be abandoned and closed?

**Comment by lipis** [comment]
I guess so :) Report back if the issue still exists

**Pull request closed without merging**
