### PR TITLE
Tactical fix to oauth version compatibility issue (Fixes #1098)

### LINKED ISSUE #1098: Current code not compatible with oauthlib v3
Issue separated out from Issue #1097.

Solution proposed by @supern8ent:

> add these to `requirements.txt`:
```
oauthlib==2.1.0
requests-oauthlib==1.1.0
```

### PR DESCRIPTION
**Pull request by rbubley**

### CODE REVIEW

**Comment by lipis** [comment]
Hmm.. I have the automatic merge.. I guess I should stop it then. WDYT?

**Comment by mdxs** [comment]
Don't know if you can select for which libraries automatic merge is (not) to be done... if that is possible: I guess that should indeed be stopped for these two (perhaps only `request-oauthlib` pinning suffices) at the moment.

**Comment by rbubley** [comment]
@lipis can do that over in #1103, with a dependabot invocation like `@dependabot ignore this dependency`

**Comment by lipis** [comment]
done

**Pull request merged**
