### PR TITLE
Deploying improvments and more

### PR DESCRIPTION
**Pull request by lipis**
`gulp deploy` doesn't reinstall by default everything now..

### CODE REVIEW

**Comment by lipis** [comment]
For some reason `gulp rebuild` works perfectly but `gulp redeploy` gives me this error: https://gist.github.com/lipis/cc5b50b923a586e72b2c

**Comment by lipis** [comment]
and I'm getting a few `Segmentation Fault: 11` from time to time (but I was getting them earlier as well)

**Comment by lipis** [comment]
Fixes #358

**Comment by lipis** [comment]
Has to do something with the gulpSequence.. https://github.com/teambition/gulp-sequence/issues/2 but no clue :)

(@gmist maybe switching to something more popular: https://github.com/OverZealous/run-sequence?)

**Comment by gmist** [comment]
interesting... will need to try and test it.

**Comment by lipis** [comment]
for now maybe I'll get rid of the broken `gulp redeploy` and move forward with this PR.. unless there are objects/comments...

**Comment by lipis** [comment]
Removed the `redeploy` for now.. will be a separate PR

**Pull request merged**
