### PR TITLE
Refactor loading graphic on buttons

### PR DESCRIPTION
**Pull request by dhstack**
Continuation of #295

### CODE REVIEW

**Comment by lipis** [comment]
So it looks good.. lets try to squash it :)

In theory if you run the following commands you should be ok :)
```bash
git reset --soft HEAD~2
git commit -m "Refactored data loading text and added spinning icon"
git push -f
```

**Comment by dhstack** [comment]
It worked!

I wasn't putting the "-f" after the push command.

**Comment by lipis** [comment]
But as @gmist mentioned in the other PR.. you will need the rebase when it comes to have updates with master :) one thing at the time..

**Comment by lipis** [comment]
And it's live on the main one :) https://gae-init.appspot.com/feedback/

**Comment by dhstack** [comment]
Looks good :)


*--*
*David Stack*
http://www.linkedin.com/in/davidstack

**Pull request merged**
