### PR TITLE
Add travis.yml

### PR DESCRIPTION
**Pull request by lipis**
Not exactly straight forward: https://cloud.google.com/solutions/continuous-delivery-with-travis-ci

### CODE REVIEW

**Comment by rbubley** [comment]
The specific bit to add is:

```
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
```

(as well as adding the `fetch_gae_sdk.py` script somewhere to the repo, or having something like
`wget https://raw.githubusercontent.com/GoogleCloudPlatform/continuous-deployment-demo/master/scripts/fetch_gae_sdk.py`)

**Comment by lipis** [comment]
Thanks @rbubley.. I'll take a look over the weekend for this one!

If you feel like you can make PR to this branch in the meantime..

**Comment by rbubley** [comment]
@lipis, can you turn Travis back on? - We can see if this has cured all the errors or just uncovered a new one to be fixed.

**Comment by lipis** [comment]
Hmm.. I'm not sure why it's not there right now.. I didn't touch anything on travis

**Comment by lipis** [comment]
Should I just merge it to master maybe so we get the travis.yml into the master and try to fix it later?!

**Comment by rbubley** [comment]
Sounds good to me.

**Comment by lipis** [comment]
Let's see then!

**Pull request merged**
