### PR TITLE
Propagate pip-related errors to run.py's return code.

### PR DESCRIPTION
**Pull request by rbubley**
This should mean that pip-related errors will now cause a Travis fail.

### CODE REVIEW

**Comment by rbubley** [comment]
Github outage meant that travis didn't check it. Only project maintainers can initiate a re-run.

**Comment by lipis** [comment]
I restarted.. you can always force push another commit to restart the task!

**Comment by rbubley** [comment]
No, nothing wrong! 🙄

**Comment by lipis** [comment]
So all green now!

**Pull request merged**
